inherit_from: .rubocop_todo.yml

inherit_gem:
  defra_ruby_style:
    - default.yml

require:
  - rubocop-factory_bot

plugins:
  - rubocop-capybara
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
