dist: trusty

addons:
  sonarcloud:
    organization: "defra"

language: ruby
rvm: 2.7.1
cache: bundler

# Travis CI uses shallow clone to speed up build times, but a truncated SCM
# history may cause issues when SonarCloud computes blame data. To avoid this,
# you can access the full SCM history with `depth: false`
git:
  depth: false

env:
  global:
    - WCRS_REGISTRATION_EXPIRES_AFTER=3
    - WCRS_REGISTRATION_RENEWAL_WINDOW=3
    - WCRS_REGISTRATION_GRACE_WINDOW=5
    - WCRS_REGISTRATION_COVID_GRACE_WINDOW=180
    - WCRS_END_OF_COVID_EXTENSION_YEAR=2020
    - WCRS_END_OF_COVID_EXTENSION_MONTH=10
    - WCRS_END_OF_COVID_EXTENSION_DAY=1
    - WCRS_USE_XVFB_FOR_WICKEDPDF=true

services:
  - mongodb

before_install:
  - export TZ=UTC
  - gem install bundler
  - sudo apt-get install xvfb -y
  - sudo apt-get install ttf-liberation -y
  - sudo apt-get install wkhtmltopdf -y

before_script:
  # Set up Mongo databases
  - mongo waste-carriers-test --eval 'db.createUser({user:"mongoUser", pwd:"password1234", roles:["readWrite", "dbAdmin", "userAdmin"]})'
  - mongo waste-carriers-users-test --eval 'db.createUser({user:"mongoUser", pwd:"password1234", roles:["readWrite", "dbAdmin", "userAdmin"]})'

script:
  - bundle exec rubocop --format progress --format json --out rubocop-result.json
  - bundle exec rspec
  - sonar-scanner
