# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c02601dfa1377be25751fcad1d65346dc77764691f16dfc448777b96701f25473d467b271064547b0174cd99c25fbd09f0217601cc09a064b5978a7e782389e

test:
  secret_key_base: e705af74d1700907a42751e0fbc77afe403a717a8dfd30dd9e77a4034636971070319489e2f2b1abb60712c6777b365a523aba6e11b9c20c5b3080c0229fd5c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
